blog/urls.py
from django.urls import path, include
from .import views  
from .feeds import LatestPostsFeed
from django.conf.urls import url
from .views import addpost
from django.contrib import admin


app_name ='blog'

urlpatterns = [
    # post views
    path('post_list', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
   
]
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    #path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('post/new/',views.addpost,name='post'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/edit',views.post_edit,name='post_edit'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/delete/', views.post_delete, name='post_delete'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/deleted/', views.post_deleted, name='post_deleted'),
    path ('<int:post_id>/share/', views.post_share, name= 'post_share'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('blogs/', views.blogs, name='blogs'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('post/', views.addpost, name='post'),
   
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings



sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'), 
    path('profile/<str:username>', user_views.profile, name='profile'), 
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),   
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'), 
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'), 
    path('ckeditor/', include('ckeditor_uploader.urls')),
    #path('myapi/', include('myapi.urls')),
                  
]
if settings.DEBUG: 
    static(settings.STATIC_URL, documents_root=settings.STATIC_ROOT)

      

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField


#...custom manager ......#
class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
	STATUS_CHOICES = (('draft', 'Draft'),('published', 'Published'),)
	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250,unique_for_date='publish')
	author = models.ForeignKey(User,
	on_delete=models.CASCADE,
	related_name='blog_posts')
	body = RichTextField(blank=True, null=True)
	#body = models.TextField()
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10,choices = STATUS_CHOICES, default='published')
	objects = models.Manager() # The default manager.
	published = PublishedManager() # Our custom manager.
	tags = TaggableManager()

	def get_absolute_url(self):
		return reverse('blog:post_detail',args=[self.publish.year,self.publish.month,self.publish.day, self.slug])

	def get_absolute_url_edit(self):
		return reverse('blog:post_edit',args=[self.publish.year,self.publish.month,self.publish.day, self.slug])

	def get_absolute_url_delete(self):
		return reverse('blog:post_delete',args=[self.publish.year,self.publish.month,self.publish.day, self.slug])

class Meta:
	ordering = ('-publish',)
	

def __str__(self):
 	return self.title

class Comment(models.Model):
	post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('-created',)
	def __str__(self):
		return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment, Post
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor.widgets import CKEditorWidget

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)
    

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')



'''class AddPostForm(forms.Form):
    Title = forms.CharField(max_length=150,widget=forms.TextInput(attrs={'id':'titleField','placeholder':'Title of Post...'}))
    Body = forms.CharField(widget=forms.Textarea(attrs={'id':'bodyfield'}))
    title = forms.CharField(widget=forms.TextInput(attrs={'id':'id_title'}))
    body = forms.CharField(widget=forms.TextInput(attrs={'id':'id_body'}))  
    
'''

class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','author','slug', 'body')

        widget = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }
class post_edit(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'id':'id_title'}))
    body = forms.CharField(widget=forms.Textarea(attrs={'id':"id_body"}))
  
    class Meta:
        model = Post
        fields = ('title', 'body')

class deletePost(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'id':'titleField'}))

blog/views.py
#...A Django view is just a Python function that receives a web request and returns a web response. All the logic to return the desired response goes inside the view...#
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post,Comment
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.views.generic import ListView,DetailView,CreateView
from django.core.mail import send_mail
from .forms import EmailPostForm,CommentForm,AddPostForm
from taggit.models import Tag
from django.db.models import Count
from blog.models import Post
from django.contrib import messages
from django.contrib.auth.models import User 
from django.contrib.auth.mixins import LoginRequiredMixin

Post.objects.filter(body__contains='framework')

def get_slug(pSlug):
    newstr = ''
    for a in pSlug:
        if (a != ' '):
            newstr = newstr + a
        else:
            newstr = newstr + '-'
    return (newstr)
 
# Create your views here.
def post_list(request):
    posts = Post.published.all()
    return render(request,'blog/post/list.html',{'posts': posts})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            
    else:
        comment_form = CommentForm()
    # List of similar post
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request,'blog/post/detail.html',{'post': post,'comments': comments,'new_comment': new_comment,'comment_form': comment_form,'similar_posts': similar_posts,})

def blogs(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 2) # 2 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    context = {
        'title':'Profile',
        'page':page,
        'tag':tag,
        'posts': posts
    }
    return render(request,'blog/blogs.html',context)
  

def aboutus(request):
    post = Post.published.all()
    return render(request,'blog/aboutus.html')


def addpost(request):
    form = AddPostForm(request.POST)
    if form.is_valid():
        pTitle = form.cleaned_data.get('title')
        pBody = form.cleaned_data.get('body')
        user = request.user 
        pSlug = get_slug(pTitle)
        post=Post(title=pTitle,body=pBody,slug=pSlug,author=request.user)
        post.save()
        return redirect(post)
        
    else:
        form = AddPostForm()
        
    context = {'form': form }
    return render(request,'blog/post.html', context)

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 2 ) # 2 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html',{'page': page,'posts': posts,'tag': tag})


def post_edit(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
    form = AddPostForm (request.POST)
    if form.is_valid():
        user = request.user 
        if post.author == user:
            nwTitle = form.cleaned_data.get('title')
            nwBody = form.cleaned_data.get('body')
            post.title=nwTitle
            post.body=nwBody
            pSlug = get_slug(nwTitle)
            post.slug = pSlug 
            post=Post(title=nwTitle,body=nwBody,slug=pSlug,author=request.user)
            post.save()
            return redirect(post)
    else:
        form = AddPostForm()     
    context = {'form': form, 'post':post}
    return render(request,'blog/post_edit.html', context)


def post_delete(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    user = request.user
    
    if user == post.author:
        post.delete()
        return redirect ('blog:blogs')
    else:
        messages.warning(request, 'You\'re not authorized to delete this post.')
        return redirect (post)

def post_deleted(request,year,month,day, post): 
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    post.delete()
    messages.success(request, f'Post successfully deleted!')
    return redirect('blog:blogs')
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'blog/post/list.html'

def post_share(request, post_id):
    # Retrieve post by id                         
    post = get_object_or_404(Post, id=post_id, status='published') 
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message,'admin@myblog.com',[cd['to']])
            sent = True 
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent}) 
    

    



        

blog/templates/blog/aboutus.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block content %}
<!DOCTYPE html>
<html>

<body>
	<section class="cta">
    <h1>For more Information about Smart meters visit the link below</h1>
    <a href="#" class="hero-btn">CONTACT US</a>
</div>


</body>
</html>
{% endblock %}

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}||BLOOM BLOG||{% endblock %}</title>
 
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">

    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&display=swap" rel="stylesheet">
</head>

<body>
    <section class="header">
        <nav>
            <a class= "mr-4" href="base.html"><img src="{% static 'css/image/logo origin.png' %}" ></a>
            <h1 style="color: #fff">BLOOM BLOG </h1>


            <div class="nav-Links" id="navLinks">
                <i class="fa fa-times" onclick="hideMenu()"></i>
                <ul>
                    <li><a href="{% url 'blog:post_list' %} ">HOME</a></li>
                    <!---<li><a href="{% url 'blog:aboutus' %}">ABOUT US</a></li>--->
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'blog:blogs' %}">BLOG</a></li>
                    <li><a href="{% url 'blog:post' %}">POST</a></li>
                    <li><a href="{% url 'profile' user.username %}">{{ user.username }}</a></li>
                    <li><a href="{% url 'logout'%}">LOGOUT</a></li>
                    {% else %}
                    <li><a href="{% url 'register' %}">SIGN UP</a></li>
                    <li><a href="{% url 'login'%}">LOGIN</a></li>
                    {% endif %}
                </ul>
            </div>
          <i class="fa fa-bars" onclick="showMenu()"></i>
         
        </nav> 
    </section>
    





    <!-----Javascript for Toogle Menu----->


<script>
    var navLinks = document.getElementById("navLinks");
    function showMenu(){
        navLinks.style.right = "0px";
    }
    function hideMenu(){
        navLinks.style.right = "-400px";
    }
</script>


    

<section>
    <div>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}

        {% endif %}
    </div>

    <div id="comment">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}

        {% endif %}
        {% block content %} {% endblock %}
    </div>
</section>
    <div class="footer">
            <h3>About Us</h3>
            <p> kjcsdbasbviaufbviubjwfbuyfsudyvsduyfivua</p>
            <h5>
                <i class="fa fa-facebook"></i>
                <i class="fa fa-instagram"></i>
                <i class="fa fa-twitter"></i>
            </h5>
            <P>
                MAde with &copy; 2021 BLOOM BLOG &mdash; by Bloom Blog
                <a href="/terms-of-use">Terms of use</a>
            </P>
    </div> 
</body>
</html>

blog/templates/blog/blogs.html
{% extends "blog/base.html" %}
{% load blog_tags %}

<html>

<div class= "container">
        {% block content %}
        {% include "textbox.html" %}

        <div class="ind">
            <h1>My Blog</h1>
             {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
      <!----------filter ------------>
        {{ post.body|truncatewords_html:20|safe }}
            {% endfor %}

            {% include "pagination.html" with page=posts %}

            {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
            {% endif %}
        </div>
        {% endblock %}
</div>


</html>

blog/templates/blog/post.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block content %}

<div class = "container post">
	<form method="post" enctype="multipart/form-data">
		<p>Add Post...</p>
			{% csrf_token %}
		<fieldset class="form-group">
			{{ form.media }}
			{{ form.as_p }}
		</fieldset>
		<br>
		<div class="form-group">
			<button class="btn btn-outline-info" type="submit">Add post</button>
		</div>
	</form>
</div>
{% endblock content %}

blog/templates/blog/post_edit.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block content %}
<div class="container">
	<p>Edit Post..</p>

	<form method="post">
		{% csrf_token %}
		<fieldset class="form-group">
		{% autoescape off %}
		{{ form.media }}
		{{ form.as_p }}
		{% endautoescape %}
	</fieldset>
	<div class="form-group">
		<Input type="submit" value="Update Post"> 
	</div>
	</form>
</div>

	<script>
		document.getElementById('id_title').value ='{{post.title}}';
		document.getElementById('id_body').innerHTML ='{{post.body}}';
		document.getElementById('id_slug').value ='{{ post.slug }}';
	</script>

{% endblock content %}