blog/urls.py
from django.urls import path, include
from .import views  
from .feeds import LatestPostsFeed
from django.conf.urls import url
from .views import addpost
from django.contrib import admin


app_name ='blog'

urlpatterns = [
    # post views
    path('post_list', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
   
]
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    #path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('post/new/',views.addpost,name='post'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/edit',views.post_edit,name='post_edit'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/delete/', views.post_delete, name='post_delete'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/deleted/', views.post_deleted, name='post_deleted'),
    path ('<int:post_id>/share/', views.post_share, name= 'post_share'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('blogs/', views.blogs, name='blogs'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('post/', views.addpost, name='post'),
   
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings



sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'), 
    path('profile/<str:username>', user_views.profile, name='profile'), 
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),   
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'), 
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'), 
    path('ckeditor/', include('ckeditor_uploader.urls')),
    #path('myapi/', include('myapi.urls')),
                  
]
if settings.DEBUG: 
    static(settings.STATIC_URL, documents_root=settings.STATIC_ROOT)

      

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField


#...custom manager ......#
class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
	STATUS_CHOICES = (('draft', 'Draft'),('published', 'Published'),)
	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250,unique_for_date='publish')
	author = models.ForeignKey(User,
	on_delete=models.CASCADE,
	related_name='blog_posts')
	body = RichTextField(blank=True, null=True)
	#body = models.TextField()
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10,choices = STATUS_CHOICES, default='published')
	objects = models.Manager() # The default manager.
	published = PublishedManager() # Our custom manager.
	tags = TaggableManager()

	def get_absolute_url(self):
		return reverse('blog:post_detail',args=[self.publish.year,self.publish.month,self.publish.day, self.slug])

	def get_absolute_url_edit(self):
		return reverse('blog:post_edit',args=[self.publish.year,self.publish.month,self.publish.day, self.slug])

	def get_absolute_url_delete(self):
		return reverse('blog:post_delete',args=[self.publish.year,self.publish.month,self.publish.day, self.slug])

class Meta:
	ordering = ('-publish',)
	

def __str__(self):
 	return self.title

class Comment(models.Model):
	post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('-created',)
	def __str__(self):
		return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment, Post
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor.widgets import CKEditorWidget

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)
    

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')



'''class AddPostForm(forms.Form):
    Title = forms.CharField(max_length=150,widget=forms.TextInput(attrs={'id':'titleField','placeholder':'Title of Post...'}))
    Body = forms.CharField(widget=forms.Textarea(attrs={'id':'bodyfield'}))
    title = forms.CharField(widget=forms.TextInput(attrs={'id':'id_title'}))
    body = forms.CharField(widget=forms.TextInput(attrs={'id':'id_body'}))  
    
'''

class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','author','slug', 'body')

        widget = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }
class post_edit(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'id':'id_title'}))
    body = forms.CharField(widget=forms.Textarea(attrs={'id':"id_body"}))
  
    class Meta:
        model = Post
        fields = ('title', 'body')

class deletePost(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'id':'titleField'}))

blog/views.py
#...A Django view is just a Python function that receives a web request and returns a web response. All the logic to return the desired response goes inside the view...#
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post,Comment
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.views.generic import ListView,DetailView,CreateView
from django.core.mail import send_mail
from .forms import EmailPostForm,CommentForm,AddPostForm
from taggit.models import Tag
from django.db.models import Count
from blog.models import Post
from django.contrib import messages
from django.contrib.auth.models import User 
from django.contrib.auth.mixins import LoginRequiredMixin

Post.objects.filter(body__contains='framework')

def get_slug(pSlug):
    newstr = ''
    for a in pSlug:
        if (a != ' '):
            newstr = newstr + a
        else:
            newstr = newstr + '-'
    return (newstr)
 
# Create your views here.
def post_list(request):
    posts = Post.published.all()
    return render(request,'blog/post/list.html',{'posts': posts})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            
    else:
        comment_form = CommentForm()
    # List of similar post
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request,'blog/post/detail.html',{'post': post,'comments': comments,'new_comment': new_comment,'comment_form': comment_form,'similar_posts': similar_posts,})

def blogs(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 2) # 2 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    context = {
        'title':'Profile',
        'page':page,
        'tag':tag,
        'posts': posts
    }
    return render(request,'blog/blogs.html',context)
  

def aboutus(request):
    post = Post.published.all()
    return render(request,'blog/aboutus.html')


def addpost(request):
    form = AddPostForm(request.POST)
    if form.is_valid():
        pTitle = form.cleaned_data.get('title')
        pBody = form.cleaned_data.get('body')
        user = request.user 
        pSlug = get_slug(pTitle)
        post=Post(title=pTitle,body=pBody,slug=pSlug,author=request.user)
        post.save()
        return redirect(post)
        
    else:
        form = AddPostForm()
        
    context = {'form': form }
    return render(request,'blog/post.html', context)

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 2 ) # 2 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html',{'page': page,'posts': posts,'tag': tag})


def post_edit(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
    form = AddPostForm (request.POST)
    if form.is_valid():
        user = request.user 
        if post.author == user:
            nwTitle = form.cleaned_data.get('title')
            nwBody = form.cleaned_data.get('body')
            post.title=nwTitle
            post.body=nwBody
            pSlug = get_slug(nwTitle)
            post.slug = pSlug 
            post=Post(title=nwTitle,body=nwBody,slug=pSlug,author=request.user)
            post.save()
            return redirect(post)
    else:
        form = AddPostForm()     
    context = {'form': form, 'post':post}
    return render(request,'blog/post_edit.html', context)


def post_delete(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    user = request.user
    
    if user == post.author:
        post.delete()
        return redirect ('blog:blogs')
    else:
        messages.warning(request, 'You\'re not authorized to delete this post.')
        return redirect (post)

def post_deleted(request,year,month,day, post): 
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    post.delete()
    messages.success(request, f'Post successfully deleted!')
    return redirect('blog:blogs')
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'blog/post/list.html'

def post_share(request, post_id):
    # Retrieve post by id                         
    post = get_object_or_404(Post, id=post_id, status='published') 
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message,'admin@myblog.com',[cd['to']])
            sent = True 
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent}) 
    

    



        

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}




<script>
  function showDelete(){
    document.getElementById("preoverlay").id="overlay";
    document.getElementById("predeldiv").id="deldiv";
  }
  function unshowDelete(){
    document.getElementById("overlay").id="preoverlay";
    document.getElementById("deldiv").id="predeldiv";
  }

</script>
<div class="container">
      
    <div id="preoverlay"></div>
    <div id="predeldiv">
      <h3>Are you sure you want to delete this post?</h3>
      <a href="{{ post.get_absolute_url_delete }}">Yes</a>
      <button id="nobtn" onclick="unshowDelete()">No</button>
    </div> 
    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    <h6>
      {% autoescape off %}
          {{ post.body|safe }}
      {% endautoescape %}
    </h6>
    <p><a href = "{% url 'blog:post_share' post.id %}">Share</a></p>

    <div class = "text-center">
      {% if user == post.author %}
      <p><a href = "{{ post.get_absolute_url_edit }}">Edit Post</a></p>
    <button class="myBtn" onclick="showDelete()">
      Delete Post
    </button>


    {% endif %}
    </div>


    <h2>Similar posts</h2>
    {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
    There are no similar posts yet.
    {% endfor %}

    {% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
    {% endwith %}

    {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
      <h2>Your comment has been added.</h2>
    {% else %}
      <h2>Add a new comment</h2>
      <form method="post">
      <fieldset>
        {{ form.media }}
        {{ comment_form.as_p }}
      </fieldset>
        {% csrf_token %}
        <p><input type="submit" value="Add comment"></p>
      </form>

</div>

{% endif %}
{% endblock content %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
   </ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
{% include "textbox.html" %}

<!------------ COURSE ---------->
<section class="course">
    <h1>The Smart Energy Research Group</h1>
    <p>
        The Research group consist of group of persons whose aim is to build smart meters
        <br>and also write Webapplications that allow the smart devices communicate with the
        <br>users it functionality, status and total energy used
    </p>
    <div>
        <h2> THE RESEARCH PROJECT HAS BEEN DIVIDED INTO MODULES SUCH AS:</h2>
    </div>
    <div class="row">
        <div class="course-col">
            <h3>Research On Smart Meters</h3>
            <p>
                This includes documentations on smart meters,
                types and off grid capacity.
            </p>
        </div>
        <div class="course-col">
            <h3>Web Development and Hardware Team</h3>
            <p>
                The web development teams build a responsive webpage for the smart devices<br>
                and the hardware team oversees the building,testing and placing of the smart meters
            </p>
        </div>
        <div class="course-col">
            <h3>The integration and Deployement Team</h3>
            <p>
                These team are in charge of deploying smart meter
                getting reports on them to the web platform regularly
                and giving feedback to other teams.
            </p>
        </div>
    </div>
</section>


<!-----Metering ----->

<section class="Metering">
    <h1> Types of Smeters Majorly used in Developed Countries</h1>
    <p></p>
    <div class="row">
        <div class="Metering-col">
            <img src="{{STATIC_URL}}/static/css/image/solar2.jpg">
            <div class="Layer">
                <h3>solar meter</h3>
            </div>
        </div>

        <div class="Metering-col">
            <img src="{{STATIC_URL}}/static/css/image/electricity meter.jpg">
            <div class="Layer">
                <h3>Electricity Meter</h3>
            </div>
        </div>
        <div class="Metering-col">
            <img src="{{STATIC_URL}}/static/css/image/water.jpg">
            <div class="Layer">
                <h3>Water Meter</h3>
            </div>
        </div>
    </div>
</section>
<!-----FACILIIES

<section class="facilities">
    <h1>Smart Meters Monitoring</h1>
    <p>The Smart Meter monitorig applications or devices are used to a consumer's energy usage, below are some pictures and descriptions.</p>
    <div class="row">
        <div class="facilities-col">
            <img src="{{STATIC_URL}}/static/css/image/gas monitoring.png">
            <h3>nPower (EON) Smart meter for gas</h3>
            <P>
                Its a monitoring device that to keep track of <br />
                your spending and see where you could<br />
                use less to save money.
                They send out accurate readings automatically, saving
                you from having to provide your meter readings every month.
            </P>
        </div>
        <div class="facilities-col">
            <img src="{{STATIC_URL}}/static/css/image/water monitor1.png" width='80' , height='200'>
            <h3>The Laison Split Type STS WATER METER</h3>
            <P>
                Its a monitoring device that to keep track of <br />
                your spending and see where you could<br />
                use less to save money.
                They send out accurate readings automatically, saving
                you from having to provide your meter readings every month.
            </P>
        </div>
        <div class="facilities-col">
            <img src="{{STATIC_URL}}/static/css/image/images (5).jpeg">
            <h3>aaoasdncon</h3>
            <P>
                jshdcaudguadcgsidcygdiygsduiyiuysdbcyubd
                hdcbsudcbisubci
            </P>
        </div>
    </div>
</section>------>

<!---tettsimonials
<section class="testimonials">
    <h1>aaoasdncon</h1>
    <P>
        jshdcaudguadcgsidcygdiygsduiyiuysdbcyubd
        hdcbsudcbisubci
    </P>
    <div class="row">
        <div class="testimonials-col">
            <img src="{{STATIC_URL}}/static/css/image/images (6).jpeg">
            <div>
                <P>
                    wgaffyYWTDVTYWCDYTWgcahcvs
                </P>
                <h3>Johnson Moyinoluwa</h3>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
            </div>
        </div>

        <div class="testimonials-col">
            <img src="{{STATIC_URL}}/static/css/image/images (6).jpeg">
            <div>
                <P>
                    wgaffyYWTDVTYWCDYTWCDcvs
                </P>
                <h3>Johnson Moyinoluwa</h3>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
            </div>
        </div>
    </div>
</section>-->

<!-- <div class="ind">
        <h1>Blog</h1>
        {% for post in posts %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <p class="tags">Tags:{% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
      ---filter 
        {{ post.body|truncatewords_html:20 }}
            {% endfor %}
            {% include "pagination.html" with page=posts %}
            {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
            {% endif %}
    </div> -->

    <!----<div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog. I've written {% total_posts %} posts so far.</p>
        <h3>Latest posts</h3>
        {% show_latest_posts 3 %}
        <h3>Most commented posts</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
            <li>
                 <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>
            <p>
                <a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a>
            </p>
        </div>---->
</div>
{% endblock %} 

blog/templates/blog/post/share.html
<!DOCTYPE html>
<html>
    {% extends "blog/base.html" %}
    {% block title %}Share a post{% endblock %}

    {% block content %}
     {% if sent %}
     <h1>E-mail successfully sent</h1>
      <p>
         "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
      </p>
        {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
        <fieldset>
            {{ form.as_p }}
            
            {% csrf_token %}
         </fieldset>
            <input type="submit" value="Send e-mail">
        </form>
  {% endif %}
{% endblock %}
</html>